from enum import StrEnum


class UserRole(StrEnum):
    ADMIN = "ADMIN"
    SALES = "SALES"
    VIEWER = "VIEWER"


class ServiceType(StrEnum):
    CREDIMPACTO_GRUPOS = "CREDIMPACTO_GRUPOS"
    CREDIMPACTO_FONDO_ROTATORIO = "CREDIMPACTO_FONDO_ROTATORIO"
    CREDIMPACTO_CREDITOS = "CREDIMPACTO_CREDITOS"
    CREDIMPACTO_PROVEEDORES = "CREDIMPACTO_PROVEEDORES"
    ACADEMIA_CURSO = "ACADEMIA_CURSO"
    CONSULTORIA_PROYECTO = "CONSULTORIA_PROYECTO"
    FUNDACION_CONVENIO = "FUNDACION_CONVENIO"
    FUNDACION_CONVOCATORIA = "FUNDACION_CONVOCATORIA"
    FUNDACION_FUNDRAISING = "FUNDACION_FUNDRAISING"
    FUNDACION_EXPERIENCIA = "FUNDACION_EXPERIENCIA"


class DealStage(StrEnum):
    PROSPECTO_IDENTIFICADO = "PROSPECTO_IDENTIFICADO"
    SENAL_DETECTADA = "SENAL_DETECTADA"
    PRIMER_CONTACTO = "PRIMER_CONTACTO"
    EN_SECUENCIA = "EN_SECUENCIA"
    REUNION_AGENDADA = "REUNION_AGENDADA"
    PROPUESTA_ENVIADA = "PROPUESTA_ENVIADA"
    NEGOCIACION = "NEGOCIACION"
    GANADO = "GANADO"
    PERDIDO = "PERDIDO"


class ActivityType(StrEnum):
    EMAIL = "EMAIL"
    LINKEDIN = "LINKEDIN"
    CALL = "CALL"
    MEETING = "MEETING"
    NOTE = "NOTE"


class SequenceStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"


class TemplateType(StrEnum):
    EMAIL_COLD = "EMAIL_COLD"
    EMAIL_FOLLOWUP = "EMAIL_FOLLOWUP"
    LINKEDIN_MESSAGE = "LINKEDIN_MESSAGE"
    LINKEDIN_TRIGGER = "LINKEDIN_TRIGGER"
    CALL_SCRIPT = "CALL_SCRIPT"
    VOICEMAIL = "VOICEMAIL"


class StepOutcome(StrEnum):
    REPLIED = "REPLIED"
    NO_REPLY = "NO_REPLY"
    BOUNCED = "BOUNCED"
    MEETING_BOOKED = "MEETING_BOOKED"


class TriggerType(StrEnum):
    EXPANSION = "EXPANSION"
    NUEVO_PROYECTO = "NUEVO_PROYECTO"
    CONVOCATORIA = "CONVOCATORIA"
    EVENTO = "EVENTO"
    PUBLICACION = "PUBLICACION"
    PRESUPUESTO = "PRESUPUESTO"
    CONTACTO_PREVIO = "CONTACTO_PREVIO"
    REFERIDO = "REFERIDO"
