from enum import StrEnum

class UserRole(StrEnum):
    ADMIN = "ADMIN"
    SALES = "SALES"
    VIEWER = "VIEWER"

class ServiceType(StrEnum):
    CREDIMPACTO_GRUPOS = "CREDIMPACTO_GRUPOS"
    CREDIMPACTO_CREDITOS = "CREDIMPACTO_CREDITOS"
    ACADEMIA_CURSO = "ACADEMIA_CURSO"
    CONSULTORIA_PROYECTO = "CONSULTORIA_PROYECTO"
    FUNDACION_CONVENIO = "FUNDACION_CONVENIO"

class DealStage(StrEnum):
    PROSPECTO_IDENTIFICADO = "PROSPECTO_IDENTIFICADO"
    PRIMER_CONTACTO = "PRIMER_CONTACTO"
    REUNION_AGENDADA = "REUNION_AGENDADA"
    DIAGNOSTICO = "DIAGNOSTICO"
    PROPUESTA_ENVIADA = "PROPUESTA_ENVIADA"
    NEGOCIACION = "NEGOCIACION"
    GANADO = "GANADO"
    PERDIDO = "PERDIDO"

class ActivityType(StrEnum):
    EMAIL = "EMAIL"
    LINKEDIN = "LINKEDIN"
    CALL = "CALL"
    MEETING = "MEETING"
    NOTE = "NOTE"
